on:
  push:
    branches:
      - '*'

  workflow_dispatch:


jobs:
  job1:
    name: test
    runs-on: ubuntu-latest
    outputs:
      regions: ${{ steps.extract.outputs.regions }}
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: extract
      shell: bash
      run: |
        # regions=$(jq -r ".locations" user_input.json)
        # json=$(jq --arg str "$regions" '.locations = ($str | split(","))' user_input.json) #> temp.json
        # echo $json
        # echo "regions=$json" >> $GITHUB_OUTPUT
        # mv temp.json user_input.json
        # regions=$(jq -r ".locations" user_input.json)
        # # Convert string to array in JSON and store the result
        # json=$(jq --arg str "$regions" '.locations = ($str | split(","))' user_input.json)

        # # Extract just the locations array from the JSON and format it for GITHUB_OUTPUT
        # # This will properly escape the JSON array for GitHub Actions
        # locations_array=$(echo "$json" | jq -r '.locations | join(",")')
        # echo "regions=$locations_array"
        # echo "regions=$locations_array" >> $GITHUB_OUTPUT
        matrix=$(jq '.' user_input.json | jq -c .)
        echo "regions=$matrix"
        echo "regions=$matrix" >> $GITHUB_OUTPUT
  
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - name: s1
      run: echo "${{ needs.job1.outputs.regions }}"

  job2:
    name: job2
    runs-on: ubuntu-latest
    needs: [job1]
    strategy:
      matrix:
        region: ${{ fromJson(needs.job1.outputs.regions).regions }} 
    steps:
    - name: s1
      run: echo "${{ matrix.region }}"

    # - name: Generate token
    #   id: generate_token
    #   uses: tibdex/github-app-token@v1
    #   with:
    #     app_id: ${{ secrets.APP_ID }}
    #     private_key: ${{ secrets.APP_PRIVATE_KEY }}

    # - name: Wait for approval
    #   uses: sunny-1651/manual-approval@dev
    #   with:
    #     secret: ${{ steps.generate_token.outputs.token }}
    #     approvers: sunny-1651
    #     minimum-approvals: 1
    #   env:
    #     target-repository: first_go_project
    #     target-repository-owner: sunny-1651

