on:
  push:
    branches:
      - '*'

  workflow_dispatch:


jobs:
  job1:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main

    - name: s1
      run: echo "hjk"

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.CLIENT_ID }}

    - name: Wait for approval
      uses: sunny-1651/manual-approval.git
      with:
        secret: ${{ steps.generate_token.outputs.token }}
        approvers: sunny-1651
        minimum-approvals: 1

    - name: s2
      run: echo "pjin"


