on:
  push:
    branches:
      - '*'

  workflow_dispatch:


jobs:
  job1:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main

    - name: s1
      run: echo "hjk"

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    # - name: docker login
    #   run: echo ${{ secrets.PAT_TOKEN }} | docker login ghcr.io -u sunny-1651 --password-stdin
        # docker login --username sunny-1651 --password ${{ secrets.PAT_TOKEN }} ghcr.io

    - name: Wait for approval
      uses: sunny-1651/manual-approval@check
      with:
        secret: ${{ steps.generate_token.outputs.token }}
        approvers: sunny-1651
        minimum-approvals: 1
        target-repository: manual-approval
        target-repository-owner: sunny-1651

    - name: s2
      run: echo "pjin"


